### PR TITLE
Add Master Tier

### PR DESCRIPTION
**Pull request by GuardianPony**
Adds Master Tier to the API, using the same general code in GetChallenger functions.

### CODE REVIEW

**Comment by BenFradet** [comment]
Hi, great work.

Would you be able to add the unit test as well, like [for the Challenger league](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharpTest/RiotApiTest.cs#L331-L349)?

**Comment by GuardianPony** [comment]
Hi, thanks.

I added the unit tests for the Master league. Using your boilerplate, as I do not have any prior experience writing unit tests.

**Comment by BenFradet** [comment]
LGTM, I'll try to run the test tonight and make a minor release before the end of the week.

**Comment by BenFradet** [comment]
Sorry for getting back to you so late but everything works fine, thanks a lot for the contrib.

**Pull request merged**
