### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by JamesMReilly**
(#270) Made changes to testing making Assertions more standards (Preferring Assert.AreEqual when possible) and comparing to more legitimate values where feasible.

Removed redundant IsNotNull Assertions.

### CODE REVIEW

**Comment by BenFradet** [comment]
Thanks a lot for this. However, could you open your PR against develop and not master?

**Comment by JamesMReilly** [comment]
Will get to this as soon as I can, Sorry! I am new to contributing to projects

**Comment by BenFradet** [comment]
no problem!

**Comment by JamesMReilly** [comment]
I am not versed in GitHub's version of git workflow. I moved my changes into a separate branch and I believe I am requesting to merge these changes with the origin/development via a pull request. However I am getting a repeated error: Sync failed to push local changes, it seems you do not have permission to push your changes to this repository.

**Comment by BenFradet** [comment]
Here's what you should do:

- [Fork the repository](https://help.github.com/articles/fork-a-repo/)
- Create a new branch in your fork starting from develop, let's say the branch name is 270_better_assertions
- Make your changes and do a commit of those changes in the 270_better_assertions branch
- [Create a pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) where you compare your fork's 270_better_assertions branch and the original repo's develop branch

**Comment by BenFradet** [comment]
Closing this, feel free to reopen it once you've figured things out.

**Pull request closed without merging**
