### PR TITLE
Added highest achieved season tier attribute to match summary

### PR DESCRIPTION
**Pull request by StevenReitsma**
See issue #104

### CODE REVIEW

**Comment by BenFradet** [comment]
The Tier class is in the ```RiotSharp.LeagueEndpoint``` namespace.

**Comment by StevenReitsma** [comment]
Thanks, Ben.

**Comment by BenFradet** [comment]
No, thank you for contributing.

**Comment by BenFradet** [comment]
I'll update the nuget tomorrow I think.

**Pull request merged**
