### PR TITLE
[Develop] Added support for current-game-v1.0 and featured-games-v1.0 endpoints [fixes #107]

### LINKED ISSUE #107: [CurrentGame Endpoint] New Riot API endpoint for summoner's current game
As of 1/29 there is a new endpoint available for the API.  It gets data from the spectator grid to retrieve the current game a summoner is playing in.

I've already gone ahead and started adding support for this endpoint, it's in my fork of the repo.  I followed the same standards as the other implemented endpoints to the best of my knowledge.  All calls to the endpoint are getting a 503 response (Riot server problem), so I'll try testing it more later when their end is up and running again.

### PR DESCRIPTION
**Pull request by mfioccop**
Support for the two newest endpoints to the API added.

Manually tested basic functionality:
+ GetCurrentGame on self in ARAM game: successful response and correct content
+ GetCurrentGame on self in custom game: 404 error (waiting on a reply from devs on the api discussion to see if customs are available through the endpoint or not)
+ GetFeaturedGames on NA region: successful response and matched content that was displayed in the client at the time

I'll try to get some unit tests done in the next few days when I have some more time.

### CODE REVIEW

**Comment by BenFradet** [comment]
Could you add the necessary unit tests? Or do you want me to do it?

**Comment by mfioccop** [comment]
I'm adding them for GetFeaturedGames right now. As far as GetCurrentGame goes, I've added one test to the Exception tests for getting a summoner's game on the wrong Platform. Should I add another for an expected 404 response when a summoner isn't in game (could make a throwaway account that will never be in a game)?

**Comment by BenFradet** [comment]
That's great, for the 404, it's up to you.

**Comment by Jeffroiscool** [comment]
Any idea when this part is done? Would love to integrate this into my bot :)

**Comment by BenFradet** [comment]
I'll try to do 2.2 this week.

**Comment by BenFradet** [comment]
Again great work and thank you for your contribution!

**Comment by Jeffroiscool** [comment]
Nuget Package? :D

**Comment by BenFradet** [comment]
No problem, I'll let you know once 2.2 is ready.

**Comment by BenFradet** [comment]
@Jeffroiscool 2.2 is out.

**Comment by Jeffroiscool** [comment]
Awesome stuff, I'm going to see if I can set it up tonight on my bot :)
Thanks again for your work! (and the contributer too of course!)

**Comment by Jeffroiscool** [comment]
Quick question, why have Riotsharp.Platform and Riotsharp.Region since
they're basically the same.
Maybe easier way would be if Region can be used as well internally and
translate it into the correct platform? :)

**Comment by Jeffroiscool** [comment]
This is what I currently use to solve it for me:

public static Platform Region2Platform(Region region)
        {
            switch (region)
            {
                case Region.br:
                {
                    return Platform.BR1;
                }
                case Region.eune:
                {
                    return Platform.EUN1;
                }
                case Region.euw:
                {
                    return Platform.EUW1;
                }
                case Region.kr:
                {
                    return Platform.KR;
                }
                case Region.lan:
                {
                    return Platform.LA1;
                }
                case Region.las:
                {
                    return Platform.LA2;
                }
                case Region.na:
                {
                    return Platform.NA1;
                }
                case Region.oce:
                {
                    return Platform.OC1;
                }
                case Region.ru:
                {
                    return Platform.RU;
                }
                case Region.tr:
                {
                    return Platform.TR1;
                }
                default:
                {
                    return Platform.EUW1;
                }
            }
        }

**Pull request merged**
