### PR TITLE
Dot net 4.6 + dot net standard

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by BenFradet** [comment]
I don't really know why the build is failing if anyone has appveyor xp

**Comment by JanOuborny** [comment]
Try running the restore command in cmd mode

**Comment by BenFradet** [comment]
@JanOuborny what do you mean by:

> Try running the restore command in cmd mode 

?

**Comment by JanOuborny** [comment]
@BenFradet  I added a comment to the corresponding code line. More [here](http://help.appveyor.com/discussions/problems/5413-calling-external-executable-causes-nativecommanderror-despite-no-apparent-error).

**Comment by BenFradet** [comment]
@JanOuborny thanks I'll try that, weird that it worked before though.

**Comment by BenFradet** [comment]
didn't work :'(

**Comment by JanOuborny** [comment]
Sadly, but now the NuGet restore worked. But no assemblies were loaded.

**Comment by BenFradet** [comment]
can't manage to make this work, closing

**Comment by JanOuborny** [comment]
@BenFradet  Can you don't delete the branch, so I can get a look at it later?

**Comment by BenFradet** [comment]
Sure :+1:

**Pull request closed without merging**
