### PR TITLE
Replaced all instances of api.pvp.net with api.riotgames.com

### PR DESCRIPTION
**Pull request by oisindoherty**
Closes issue [Move to the api.riotgames.com domain #347](https://github.com/BenFradet/RiotSharp/issues/347)

### CODE REVIEW

**Comment by oisindoherty** [comment]
Looked into it and found that the variable wasn't referenced anywhere else in the codebase, so I went ahead and removed it. Unit tests still run fine.

**Comment by JanOuborny** [comment]
I'm afraid this PR doesn't fully meet the requirements. Just changing the main part of the url doesn't lead to valid domains, because the region names are not equal with the platform names.

**Comment by oisindoherty** [comment]
I see, my apologies. I'll replace the references to `region` in the RateLimitedRequester with `GetPlatformDomain(region)`. As far as I can tell, they only show up in the CreatePostRequest and CreatePutRequest functions used solely by the tournament API, which explains why I missed the unit tests on them. Are there any other fixes that I'm missing? 

With regards to "Furthermore, most of the changes will be removed anyway because they will not be hit", would you suggest removing the `usePlatforms` parameter from the [CreateGetRequest function in the RateLimitedRequester?](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Http/RateLimitedRequester.cs#L27-L33) As far as I can tell, all V3 endpoints of the API use the platform names, and all current calls to CreateGetRequest for the V3 endpoints have `usePlatforms` as true.

**Comment by JanOuborny** [comment]
Regardings the `usePlatforms` parameter: It's only purposes was to signal when to use platform domains instead of the region domains. This was neccessary to use v3 and pre-v3 endpoints simultaneously, but now it can be removed. I'm currently working on some migration stuff, so let me do it.

**Comment by oisindoherty** [comment]
Sounds good, I can start working on migrating some endpoints to V3. I've done some preliminary work on CHAMPION-MASTERY-V3, does this conflict with your work?

**Comment by JanOuborny** [comment]
@oisindoherty I'm already done with champion mastery as of now. See #444

**Comment by oisindoherty** [comment]
@JanOuborny Oh gosh, didn't see that. I can start work on implementing the new RUNES-V3 endpoint. It was assigned to @nickwilliamsnewby, but we haven't heard a response in three weeks from him. I'll respond in that issue thread as well.

**Pull request merged**
