### PR TITLE
Changed type of Partype from enum to string

### PR DESCRIPTION
**Pull request by CommanderJo**
Changed type of Partype from enum to string. Removed ParTypeStatic and ParTypeStaticConverter

### CODE REVIEW

**Comment by BenFradet** [comment]
Thanks a lot, merging!

Do you need a release quickly, or are you fine waiting for a couple of weeks / building from develop?

**Comment by CommanderJo** [comment]
I would prefer a quick release if it's ok for you.

**Comment by BenFradet** [comment]
I'll try doing one tonight then :+1:

**Comment by BenFradet** [comment]
Just uploaded 2.5.5! If you feel you can help out with the other enums that need converting to string that'd be great!

**Comment by CommanderJo** [comment]
Thanks a lot. I'm going to try to convert some enums later today.

**Pull request merged**
