### PR TITLE
Update version to 5.0.0-alpha including updated nuget package.

### PR DESCRIPTION
**Pull request by selmaohneh**
I updated the version to `5.0.0-alpha`.

Here is the generated `.nupkg`. I changed the extension to `.zip` to be able to upload it here to github. Just change it back before uploading it to nuget.org.

[RiotSharp.5.0.0-alpha.zip](https://github.com/BenFradet/RiotSharp/files/6676850/RiotSharp.5.0.0-alpha.zip)

Is this all you need or am I missing something?

### CODE REVIEW

**Review by BenFradet — COMMENTED** [review]
PR looks good, I'd need a .nupkg to upload it though

**Comment by selmaohneh** [comment]
> PR looks good, I'd need a .nupkg to upload it though

Please read the PR description again! I added the .nupkg as .zip!

**Comment by selmaohneh** [comment]
Bump

**Review by BenFradet — COMMENTED** [review]
it's going through validation

**Pull request merged**
