### PR TITLE
Tournament api

### PR DESCRIPTION
**Pull request by jvanvugt**
#153

### CODE REVIEW

**Comment by BenFradet** [comment]
Yup, tests are running, thanks.

**Comment by BenFradet** [comment]
I converted the library to pcl since you opened the PR and `Serializable` is not provided, so you'll have to remove those.

**Comment by StevenReitsma** [comment]
That won't affect any of the serialization capabilities since we're using Json.NET anyway, right? I'll make the changes tonight.

**Comment by BenFradet** [comment]
This is api key related, I'll trigger a new build.

**Comment by BenFradet** [comment]
Welp, there seems to be a problem with my api keys, I'll investigate tonight.

**Comment by BenFradet** [comment]
Unfortunately, he CI doesn't allow secure environment variable on PR, that's why the tests are failing.
I'll try the changes locally.

**Comment by BenFradet** [comment]
GetTorunamentCodeDetails{,Async} are failing on my side.

**Comment by StevenReitsma** [comment]
That could be due to the fact that GetTournamentCodeDetails can only be called with the API key it was created with. Would the error message confirm that, or is it something entirely different? The test passes for me. `GetTournamentCodeDetails` is also tested in the `CreateProvider_CreateTournament_CreateTournamentCode_UpdateTournamentCode_Test` test, so removing the `GetTournamentCodeDetails{,Async}_Test` should be fine.

**Comment by BenFradet** [comment]
Yup, that's what I was thinking seeing the code: might as well remove it.

**Comment by BenFradet** [comment]
I'll make another pass at the tests and merge if everything goes well.

**Comment by BenFradet** [comment]
Merging, thanks a lot.

**Comment by StevenReitsma** [comment]
Nice!

**Pull request merged**
