### PR TITLE
Add a top-level Cache namespace #501

### PR DESCRIPTION
**Pull request by Oucema90**
Move Cache classes to the new namespace.

### CODE REVIEW

**Comment by Oucema90** [comment]
Since it regroups multiples Cache; plural form is more suitable here. Also there will be a confusion if we use Cache as name space and Cache as class.

**Comment by JanOuborny** [comment]
What about renaming it to `Caching`? This naming is also used by Microsoft in AspNetCore.

**Comment by Oucema90** [comment]
@JanOuborny PR updated.

**Comment by BenFradet** [comment]
@Oucema90 could you rebase against develop? I'll merge right after that 👍

**Comment by Oucema90** [comment]
@BenFradet PR updated.

**Pull request merged**
