### PR TITLE
Added RiftHerald

### PR DESCRIPTION
**Pull request by tbrickey022**
Added support for the Rift Herald into the Monster Type Converter

### CODE REVIEW

**Comment by BenFradet** [comment]
Thanks! Do you need a release quickly or are you fine building from develop for a couple of weeks?

**Comment by tbrickey022** [comment]
A quick release would be great, but if it's too much trouble for such a
little change I can try and build from develop.

**Comment by BenFradet** [comment]
I'll try to release today 👍

**Comment by tbrickey022** [comment]
Awesome!  Thank you so much!

**Comment by BenFradet** [comment]
released, it should be available soon

**Comment by tbrickey022** [comment]
Got it!  Thank you again!

**Pull request merged**
