### PR TITLE
Put 3 API Classes behind Interfaces

### PR DESCRIPTION
**Pull request by Dorgenedge**
Basically I just created Interfaces for each of the major API classes. I did this for two reasons:

Firstly, it allows for better use of Dependency Injection (specifically in Unit Testing). I can now Mock these objects to test code that would otherwise depend upon the results of API calls.

Secondly, it helps with Inversion of Control a bit.

Any questions or concerns, just lemme know.

Love the project and I'm using it in a personal project!

EDIT: Created an Issue about this earlier, then realized I could do it myself quickly with little effort. If you can associate this with the issue or just remove the issue, go ahead.

### CODE REVIEW

**Comment by BenFradet** [comment]
LGTM, I'll try to look into it a bit further today.
I will close the issue when I'll merge (#136).

**Comment by BenFradet** [comment]
Merging, thanks for your contribution!

**Comment by Dorgenedge** [comment]
When is your next scheduled NuGet push? If you don't mind me asking.

**Comment by BenFradet** [comment]
I'll try to do one tonight.

**Pull request merged**
