### PR TITLE
Update tests so they can pass with valid key

### PR DESCRIPTION
**Pull request by JacobSnyder**
As long as you provide a valid API key now, the tests should pass.  It took a while to find summoner IDs and team IDs that would cause the tests to pass.  This is really just a convenience for other contributors.

### CODE REVIEW

**Comment by BenFradet** [comment]
Great idea, would you mind doing the same thing for [the example project's config file](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharpExample/App.config)?

**Comment by JacobSnyder** [comment]
Sure thing.  I'll update this PR tonight.

**Comment by BenFradet** [comment]
Great thanks.

**Comment by JacobSnyder** [comment]
With a valid API key, the output of the Example project is now:

    en_US, cs_CZ, de_DE, el_GR, en_AU, en_GB, en_PH, en_PL, en_SG, es_AR, es_ES, es_MX, fr_FR, hu_HU, id_ID, it_IT, ja_JP, ko_KR, ms_MY, pl_PL, pt_BR, ro_RO, ru_RU, th_TH, tr_TR, vn_VN, zh_CN, zh_MY, zh_TW
    SummonersRift
    Rek'Sai
    Done! Press Enter to exit.

**Comment by BenFradet** [comment]
Great work, thanks for your contrib!

**Pull request merged**
