### PR TITLE
Match api v3

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by BenFradet** [comment]
@Shidesu you'll most likely need to have a copy of this branch in your fork for code review.

**Comment by Shidesu** [comment]
There's an excedent braces at the end of the RiotApi.cs file.

**Comment by Shidesu** [comment]
Ah yeah. When made I will made a pull request into the match-api-2 branch ?

**Comment by BenFradet** [comment]
No you can open a PR against develop containing the commits in this PR\ too

**Comment by BenFradet** [comment]
superseded by #473

**Pull request closed without merging**
