### PR TITLE
Change lobby events' event type

### PR DESCRIPTION
**Pull request by Ostrea**
Change its type from string to enum as said in #185. I would like to test it, but I don't have tournament api key, so I would be glad if you can test it on your end.

### CODE REVIEW

**Comment by BenFradet** [comment]
We usually put the enums in their own file like for [TournamentMapType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/TournamentEndpoint/Converters/TournamentMapType.cs).

**Comment by Ostrea** [comment]
Will move it to different file. Should I put JsonConverter on enum or on property?

**Comment by Ostrea** [comment]
Moved to its own file and placed JsonConverter on the type

**Comment by BenFradet** [comment]
LGTM, could you add some documentation like in the previously linked TournamentMapType?

**Comment by Ostrea** [comment]
Will do it tomorrow

**Comment by BenFradet** [comment]
Sure, no problem.

**Comment by Ostrea** [comment]
I have added documentation.

**Comment by BenFradet** [comment]
LGTM

However, I'd prefer the name of the enum to be `TournamentEventType` to avoid confusions.
Also, the enum should be in the `Converters` folder like the other enums.

**Comment by Ostrea** [comment]
Done

**Comment by BenFradet** [comment]
LGTM merging, thanks.

**Pull request merged**
