### PR TITLE
File Cache - Cache for summoner and matches - Test Project Fixes

### PR DESCRIPTION
**Pull request by Talha-T**
Test project still needs some work.
Also I didn't implement GameQueueType and GameQueueConverter classes.

### CODE REVIEW

**Comment by JanOuborny** [comment]
Can you create a new branch of the latest version of the develop branch and then add your new classes `CacheData` and `FileCache` there, so we have a clean PR.

**Comment by Talha-T** [comment]
I am not sure how to do that, can you help me?

**Comment by JanOuborny** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by Talha-T** [comment]
I did it, nothing changed.

**Comment by Talha-T** [comment]
See #499 , closing.

**Pull request closed without merging**
