### PR TITLE
Dynamic Queue Type added to respective files 

### LINKED ISSUE #191: Dynamic Queue Type Missing From Queue.cs and QueueConverter.cs
The introduction of dynamic queue breaks JSON.Net's ability to deserialize any matches tied to the new dynamic queue system.

The new queue type "TEAM_BUILDER_DRAFT_RANKED_5x5" was added.

Sample JSON:

   "region":"NA",
         "platformId":"NA1",
         "matchId":2073287371,
         "champion":412,
         "queue":"TEAM_BUILDER_DRAFT_RANKED_5x5",
         "season":"SEASON2016",
         "timestamp":1453329688907,
         "lane":"BOTTOM",
         "role":"DUO_SUPPORT"

### PR DESCRIPTION
**Pull request by KreepN**
Added enumerations for new queue type - Fixes #191

### CODE REVIEW

**Comment by BenFradet** [comment]
As said in #191, this has already been added in #190.

**Comment by KreepN** [comment]
My bad on that one.

**Comment by BenFradet** [comment]
No problem.

**Comment by KreepN** [comment]
It would seem that 190 did not in fact edit these files causing http://i.imgur.com/FMbouov.png 

I think I need to add a few more lines to cover the new Dynamic Queue unranked and possibly submit a new pull request. What do you think?

**Comment by BenFradet** [comment]
Are you building from source or using the nuget?
Because the nuget hasnt been updated yet

**Comment by KreepN** [comment]
Pulling directly from the develop branch of your repo as you commit changes.

**Pull request closed without merging**
