### PR TITLE
Interceptor for wrapped riot api calls.

### PR DESCRIPTION
**Pull request by murilogibim**
I created some interceptor events which can be subscribed in order to get detailed information about the calls being made to the riot api.

I needed that in order to audit the calls being made in my app, it's my first time as a contributor of this project, let me know if I missed anything.

Thanks.

### CODE REVIEW

**Comment by BenFradet** [comment]
LGTM, thanks for including the unit tests.
It might be good to document this new feat in the readme though.

**Comment by murilogibim** [comment]
I'll do that later, kind busy on work these days... I may have some time at night to check it out :)

**Comment by BenFradet** [comment]
pinging @murilogibim if you want to update this you might want to rebase and include the documentation, otherwise I'll close this.

**Comment by BenFradet** [comment]
Closing this for now, @murilogibim will reopen if he wants to.
cf #139

**Pull request closed without merging**
