### PR TITLE
New PR for the dotnet core WIP

### PR DESCRIPTION
**Pull request by ddurschlag**

### CODE REVIEW

**Comment by BenFradet** [comment]
It seems like you've got the wrong history, same as the old PR. What you need to do is create another branch, cherry-pick your two commits: 4886358 and 498e6f6, open a PR with this branch.

**Comment by ddurschlag** [comment]
Which base would you like me to branch from -- develop or master?

**Comment by BenFradet** [comment]
develop

**Comment by ddurschlag** [comment]
Apparently still bad history...

**Pull request closed without merging**
